export const SET_ERROR_TRUE = "SET_ERROR_TRUE";
export const SET_ERROR_FALSE = "SET_ERROR_FALSE";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const SETUP_PARAMS = "SETUP_PARAMS";

export const GET_CONSISTENCY_DATA_FETCH = "GET_CONSISTENCY_DATA_FETCH";
export const GET_CONSISTENCY_DATA_SUCCESS = "GET_CONSISTENCY_DATA_SUCCESS";
export const GET_CONSISTENCY_DATA_FAILED = "GET_CONSISTENCY_DATA_FAILED";
