export const SUBMIT_PENDAFTARAN_AAJI = "SUBMIT_PENDAFTARAN_AAJI";
export const PENDAFTARAN_AAJI_GET_FORM = "PENDAFTARAN_AAJI_GET_FORM";
export const PENDAFTARAN_AAJI_PUSH_FORM = "PENDAFTARAN_AAJI_PUSH_FORM";
export const PENDAFTARAN_AAJI_TO_DEFAULT = "PENDAFTARAN_AAJI_TO_DEFAULT";
